services:
  azurite:
    # Local Azure Storage emulator providing blob, queue, and table services
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    networks:
      - func-network
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNoBnZf6KgBVU4=

  cippapi:
    # Azure Functions host running the CIPP API
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Configuration values are passed through environment variables.
      # These names match the existing implementation.
      - FUNCTIONS_WORKER_RUNTIME=${FUNCTIONS_WORKER_RUNTIME}
      - FUNCTIONS_WORKER_RUNTIME_VERSION=${FUNCTIONS_WORKER_RUNTIME_VERSION}
      - AzureWebJobsStorage=${AzureWebJobsStorage}
      - ApplicationID=${ApplicationID}
      - ApplicationSecret=${ApplicationSecret}
      - RefreshToken=${RefreshToken}
      - TenantID=${TenantID}
      - DEV_SKIP_BPA_TIMER=${DEV_SKIP_BPA_TIMER}
      - DEV_SKIP_DOMAIN_TIMER=${DEV_SKIP_DOMAIN_TIMER}
      - SetFromProfile=${SetFromProfile}
      - FUNCTIONS_EXTENSION_VERSION=${FUNCTIONS_EXTENSION_VERSION}
      - AzureWebJobs.BestPracticeAnalyser_OrchestrationStarterTimer.Disabled=true
      - AzureWebJobs.Domain_OrchestrationStarterTimer.Disabled=true
      - WEBSITE_HOSTNAME=cippapi
    depends_on:
      - azurite
    networks:
      - func-network
    deploy:
      replicas: 3

  nginx:
    # Reverse proxy exposing the Functions host on a standard port
    image: nginx:alpine
    container_name: nginx
    ports:
      - "7071:80" # API available on localhost:7071
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cippapi
    networks:
      - func-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cippapi:80/upmon"]
      interval: 30s
      retries: 5

networks:
  func-network:
    driver: bridge
